modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "heroic"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "heroic.png"
credits = "${mod_authors}"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.heroic]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.heroic]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
